# Step 1: Use official Node.js image
FROM node:18-alpine

# --- NETFREE CERT INTSALL ---
    ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh 
    RUN cat  /home/netfree-unix-ca.sh | sh
    ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
    ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
    ENV SSL_CERT_FILE=/etc/ca-bundle.crt
    # --- END NETFREE CERT INTSALL ---

# Step 2: Set working directory in the container
WORKDIR /app
# Step 3: Copy package.json and package-lock.json and install dependencies
COPY package*.json ./
RUN npm install
# Step 4: Copy the rest of the application files
COPY . .
# Step 5: Expose port 5000 (backend API)
EXPOSE 3000
# Step 6: Start the application
CMD ["npm", "start"]






