

version: "3.8"
services:
  frontend:
    build:
      context: .
    ports:
      - "3001:3000"
    # depends_on:
    #   - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge