const colorMap = {
    פליז:"#B5A642",
    עץ:"#E6CBA8",
    חלודה:"#8B3103",
    אלון:"#A67B5B",
    דובדבן:"#B22222",
    נחושת:"#C87533",
    רוזגולד:"#B76E79",
   זהב: "#B8860B  ",
    שחור: "black",
    בזלת: "darkgray",
    אפור: "gray",
    כסף: "silver",
    אפור_כהה: "darkgray",
    אפור_בהיר: "lightgray",
    לבן: "white",
    כחול: "blue",
    כחול_כהה: "darkblue",
    כחול_בהיר: "lightblue",
    תכלת: "skyblue",
    ירוק: "green",
    ירוק_כהה: "darkgreen",
    ירוק_בהיר: "lightgreen",
    צהוב: "yellow",
    צהוב_כהה: "#CCCC00",
    צהוב_בהיר: "#FFFF99",
    כתום: "orange",
    כתום_כהה: "#FF8C00",
    כתום_בהיר: "#FFD580",
    אדום: "red",
    אדום_כהה: "darkred",
    אדום_בהיר: "#FF6666",
    בורדו: "#800000",
    ורוד: "pink",
    ורוד_כהה: "deeppink",
    ורוד_בהיר: "lightpink",
    סגול: "purple",
    סגול_כהה: "darkpurple",
    סגול_בהיר: "#D8BFD8",
    חום: "brown",
    חום_כהה: "#8B4513",
    חום_בהיר: "#D2B48C",
    בז: "beige",
    שמנת: "#FFF5E1",
    ברונזה: "#CD7F32",
    טורקיז: "turquoise",
    טורקיז_כהה: "#008B8B",
    טורקיז_בהיר: "lightseagreen",
    מנטה: "#98FF98",
    זית: "olive",
    חרדל: "#FFDB58",
    קורל: "coral",
    סלמון: "salmon",
    חציל: "#311432",
  };
  export default colorMap;
