# Step 1: Use official Node.js image for React build
FROM node:18-alpine
# --- NETFREE CERT INTSALL ---
    ADD https://netfree.link/dl/unix-ca.sh /home/netfree-unix-ca.sh

    RUN cat  /home/netfree-unix-ca.sh | sh
    ENV NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt
    ENV REQUESTS_CA_BUNDLE=/etc/ca-bundle.crt
    ENV SSL_CERT_FILE=/etc/ca-bundle.crt
    # --- END NETFREE CERT INTSALL ---
# Step 2: Set working directory in the container
WORKDIR /app
# Step 3: Copy package.json and package-lock.json and install dependencies
COPY package*.json ./
RUN npm install
# Step 4: Copy the rest of the application files
COPY . .
# Step 5: Build the React app for production
# RUN npm run build
# Step 6: Install a simple web server (serve) to serve the build files
# FROM nginx:alpine
# Step 7: Copy the build files from the build stage to the Nginx container
# COPY --from=build /app/build /usr/share/nginx/html
# Step 8: Expose port 80 to access the app
EXPOSE 3000
# Step 9: Use Nginx to serve the app
CMD ["npm", "start"]

