version: "3.8"
services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=CONN_STRING
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local





